name: Feature Request
description: Suggest a new feature or enhancement for the portfolio template
title: "[FEATURE]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "THIS SH*@4 DOESN'T DO WHAT I WANT IT TO"
    validations:
      required: true
  
  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What area does this feature relate to?
      options:
        - UI/UX Enhancement
        - New Component
        - Blog System
        - Data Management
        - Performance
        - Accessibility
        - Documentation
        - Developer Experience
        - Other
    validations:
      required: true
  
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: "I would like to have..."
    validations:
      required: true
  
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or links
      placeholder: "Any additional information..."
